Home activity ui  and new game activity ui  is developed and connected with json data
IE-NITK/Redemption pull request #5
Opened 2021-01-02 07:34 UTC by Satyamjyotsanagargee

2021-01-02 07:41 UTC, dwaipayan05 reviewed
Everything Looks Good, few changes to be made in the Credits Page later!  Look out for the other reviews

2021-01-02 08:04 UTC, prakritigoyal19 requested changes
While submitting the pr, the commit messages, pr message and titles are crucial. These are stored for a long time and should be self explanatory for anyone who decides to go through them. Please write the pr message and commit messages appropriately. You can go through this link for a better understanding of how these are done. 
https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

Also do sign your commits. You need to have your contributions shown! :)

2021-01-02 08:04 UTC, prakritigoyal19 commented on local.properties
>  # header note.
Please do not commit this file

2021-01-02 08:04 UTC, prakritigoyal19 commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
Usually the .* files are hidden files and most of the time they are not meant to be committed. Please do not commit this file.

2021-01-02 08:04 UTC, prakritigoyal19 commented on .settings/org.eclipse.buildship.core.prefs
> +arguments=
Please do not commit this file.

2021-01-02 08:04 UTC, prakritigoyal19 commented on .vscode/launch.json
> +{
Please do not commit this file.

2021-01-02 08:04 UTC, prakritigoyal19 commented on app/src/main/java/com/example/ieapp/HomeActivity.java
> +                startActivity(new Intent(getApplicationContext(), Credits.class));
These changes, could maybe be done the first time you write the functions. They could be made in the previous commit itself.

2021-01-02 08:04 UTC, prakritigoyal19 commented on app/src/main/java/com/example/ieapp/HomeActivity.java
> +        play = (Button) findViewById(R.id.button4_play);
This change could be added in the previous commit.

2021-01-02 08:04 UTC, prakritigoyal19 commented on app/src/main/java/com/example/ieapp/HomeActivity.java
> +        ring = MediaPlayer.create(HomeActivity.this, R.raw.games_of_part_4);
This change could be added in the previous commit.

2021-03-18 16:12 UTC, dwaipayan05 commented
Closing this ! PR #7 Merged Accommodated these changes.

2021-03-18 16:12 UTC, closed without merging